
version: "3"
services:
  web:
    image: nginx:latest
    # restart: always
    environment: 
      - verbosity="debug"
    ports:
      - 9000:80
    volumes: 
      - ./index.html:/usr/share/nginx/html/index.html

